---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - secrets.yaml
    - dovars.yaml
  tasks:
    - name: create App host
      digital_ocean_droplet:
        state: present
        name: "{{apphost_name}}" 
        size: "{{apphost_size}}"
        region: "{{apphost_region}}"
        image: "{{apphost_image}}"
        oauth_token: "{{do_token}}"
        unique_name: yes
        ssh_keys: ["{{apphost_ssh_key}}"]
      register: apphost
    - name: debug
      debug:
        var: apphost.data.ip_address
    - name: put App host to inventory
      add_host:
        name: "{{apphost.data.ip_address}}"
        groups: app
        when: apphost.data is defined
      changed_when: False

- hosts: app
  remote_user: root
  roles:
    - app

