- name: build docker image
  docker_image:
    name: "jenkins"
    path: "{{build_dir}}"
    force: yes
    state: build

- name: remove container
  docker_container:
    name: jenkins
    state: absent

- name: start container
  docker_container:
    name: "jenkins"
    image: "jenkins"
    state: started
    published_ports: 127.0.0.1:8080:8080
    restart_policy: "unless-stopped"


