---
- name: let jenkins to ssh
  authorized_key:
    user: root
    key: "{{ lookup('file', '{{playbook_dir}}/roles/jenkins/files/id_rsa.pub') }}"

- name: create docker config dir
  file:
    path: "/root/.docker/"
    state: directory
    mode: 0755

- name: set docker login
  copy:
    src: "{{playbook_dir}}/roles/jenkins/files/config.json"
    dest: "/root/.docker/config.json"

- name: install pip
  apt:
    name: python3-pip
    update_cache: yes
    state: present

- name: install docker module
  pip:
    name: docker
