- name: create Jenkins group
  group:
    name: jenkins
    gid: 1000

- name: create Jenkins user on host and add it docker group
  user:
    name: jenkins
    uid: 1000
    group: jenkins
    groups: docker
    append: yes

- name: install pip
  apt:
    name: python-pip
    state: present

- name: install docker module
  pip:
    name: docker

- name: create temp dir to build Jenkins docker
  file:
    dest: "{{build_dir}}"
    state: directory

- name: copy files to build Jenkins container
  copy: 
    src: "docker_image/" 
    dest: "{{build_dir}}" 
  register: dockerfile

- name: build docker image
  docker_image:
    name: "jenkins"
    build:
      pull: no
      path: "{{build_dir}}"
    source: build
    force_source: yes
  when: dockerfile.changed
  register: dockerbuilt

- name: remove container
  docker_container:
    name: jenkins
    state: absent
  when: dockerbuilt.changed

- name: start container
  docker_container:
    name: "jenkins"
    image: "jenkins"
    state: started
    privileged: yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    published_ports: 127.0.0.1:8080:8080
    restart_policy: "unless-stopped"


